services:
  - type: worker
    name: hermes-telegram-bot
    env: docker
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8597102492:AAEx0lD3Ka552ln32eqrUKnuqE2RXFU3H9M"
      - key: GATEWAY_ALLOW_ALL_USERS
        value: "true"
      - key: HERMES_HOME
        value: "/app/.hermes"
      - key: OPENROUTER_API_KEY
        value: "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."
      - key: HERMES_MODEL
        value: "meta-llama/llama-3.3-70b:free"
